### ISSUE TITLE
Can't start the chat using the Chat Widget Visitor SDK

### ISSUE THREAD

**Issue by tksw** [livechat/chat-widget-sample#11]
I'm having an issue getting a chat session to start using the Chat Widget Visitor SDK. The app I'm developing for my client is loosely based on this project (chat-widget-sample). Using my own LiveChat test account and one of my client's accounts, I can successfully start a chat session using the `startChat` SDK call. However with another client's license, I'm never able to start a chat session. The standard web widget on their website works as expected.

I've tracked it down in the `@livechat/livechat-visitor-sdk` package code to the ping response received in the `pingersCaller` function. After it makes a call to `sendPostToWebserv` with the `ping` method name, I get a response value of `{next_ping_delay: 0}`. This ultimately causes the property `clientlimitexceeded` to be set to `true` and many saga tasks to be cancelled.

![image](https://user-images.githubusercontent.com/30007754/55081613-8e94f300-5076-11e9-8542-9cc0b3dec295.png)

For the 2 licenses that work, I get a response with `next_ping_delay` set to 5, and therefore it continues to ping the server after 5 seconds.

**Questions**
* Is there a configuration I'm missing in the LiveChat admin page settings for this client that is causing this ping response?
* Under what conditions does the `ping` call fail like this?
* Is there a notification or callback that is provided so that my app knows this is happening?

Thanks in advance for your help!

**Comment by ZiggyKraus** [comment]
Hello @tksw,

First of all, my apologies for the delayed response. I'm here with an update on why your VisitorSDK implementation is failing for the license with the following ID: **10241907**.

It appears that the license for which the problem occurs is using our latest version of API (LC3, API v3). The reason for the server throwing the `{next_ping_delay: 0}` response is that, due to the changes in communication protocol, VisitorSDK does not work with licenses using the latest version of our API. For those licenses, we have prepared an updated JS SDK, called **CustomerSDK** – you can check it out here: https://developers.livechatinc.com/beta-docs/customer-sdk/ and use it to make the necessary changes to your project.

@tksw once again, my apologies for a late response. In case of any additional questions and/or concerns, feel free to ask! Oh, and one more thing: the docs are marked as **beta,** but you can feel free to use them and adjust your application, as this is a fully-supported and up-to-date version of our SDK.

**Comment by tksw** [comment]
@ZiggyKraus, thanks for the update.  Will the new **CustomerSDK** work with the old version of the API? I'm supporting multiple clients for this project. The existing VisitorSDK is working with the 2 other license IDs I'm using. I want to make sure that the new **CustomerSDK** will work with the older API version (if indeed these IDs are still using the older API).

**Comment by ZiggyKraus** [comment]
@tksw, you're more than welcome! As to your second question: unfortunately, **CustomerSDK** will not work with the old version of LiveChat API (LiveChat 2 for future reference). At the moment, **VisitorSDK** should be used only with LC2 and **CustomerSDK** only with LC3, due to the differences in communication protocol facilitated by those APIs.

**Comment by tksw** [comment]
@ZiggyKraus, when making a connection using a given client ID, how can I determine if the API I'm connecting to is LC2 or LC3?

**Comment by Andarist** [comment]
With CustomerSDK you can only connect to LC3, same thing for VisitorSDK - it only handles LC2.

**Comment by ZiggyKraus** [comment]
@tksw you could send a GET request to the following endpoint:
`https://api.livechatinc.com/v2/agents/me`

and authorize it with the use of BasicAuth (email and API key of an agent from the LiveChat license in question). As a response, you should receive the following object:

`"instances": [
    {
      "push": false,
      "app_info": "Web",
      "version": "2.0",
      "ip": "1.1.1.1",
      "session_id": 2,
      "descriptor": 176
    },`

The `version` indicated which API your licenses uses (2.0 stands for LiveChat 2 and 3.0 stands for LiveChat 3) 🙂

**Comment by tksw** [comment]
@ZiggyKraus Thanks again for the continued help. Quick question: I'm supporting 3 clients as of right now. Is there any way to force the use of LC3 for particular licenses from your side so I just have to support the CustomerSDK API?

**Comment by tksw** [comment]
@ZiggyKraus If it is possible to force the LiveChat-side API to a particular version for a given license, I'd like to put the 3 clients at LC2 until I have a chance to upgrade to CustomerSDK.  Right now, they cannot use the desktop app that I've written. Is that possible?

**Comment by tksw** [comment]
Hi @ZiggyKraus - Any update on my question above? Is it possible to force my client's licenses to use LC2 instead of LC3?  - Thanks!

**Comment by ZiggyKraus** [comment]
@tksw So sorry for the late reply! I will do my best to provide you with all the necessary answers. I can roll-back the LiveChat version from 3 to 2 temporarily, so that you will be able to adjust your implementation to CustomerSDK :) All that I would need is the IDs licenses and a simple verification process, but if that's OK, I'd like to discuss it over an email - if that's OK with you, please don't hesitate to let me know and I will make all the necessary arrangements!

**Comment by tksw** [comment]
@ZiggyKraus Yes, please. That would be great!  My email is tksw@tksoftwareconsulting.com
